#!/bin/bash
#SBATCH --nodes=1                           # node count
#SBATCH --ntasks=1                          # total number of tasks across all nodes
#SBATCH --cpus-per-task=1                   # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                            # number of gpus per node
#SBATCH --partition=gpu_h100            # partition
#SBATCH --time=00:10:00                     # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j_%x.log  # output file

############################################################
source .venv/bin/activate
python -c "import torch; print('Torch version:', torch.__version__); print('CUDA check:', torch.cuda.is_available())"  # check torch version
############################################################

# models to use:
# Qwen/Qwen2-1.5B-Instruct

python src/finetune.py \
  --model Qwen/Qwen2-1.5B-Instruct \
  --wmt22_data_dir data/wmt22 \
  --wmt24pp_data_dir data/wmt24pp \
  --learn_rate 1e-3 \
  --epochs 1 \
  --batch_size 8 \
  --dtype float16 \
  --seed 381 \
  --lora_r 8 \
  --lora_alpha 8 \
  --lora_dropout 0.1 \
  --biomedical_lang "de" \
