#!/bin/bash
#SBATCH --nodes=1                           # node count
#SBATCH --ntasks=1                          # total number of tasks across all nodes
#SBATCH --cpus-per-task=1                   # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                            # number of gpus per node
#SBATCH --partition=gpu_h100            # partition
#SBATCH --time=08:00:00                     # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j.log            # output file

############################################################
cd ~/dl4nlp-project  # sanity check, for snellius
source .venv/bin/activate
python -c "import torch; print('Torch version:', torch.__version__); print('CUDA check:', torch.cuda.is_available())"  # check torch version
############################################################

# some models to use:
# Qwen/Qwen2-7B
# Qwen/Qwen2-1.5B-Instruct
# Qwen/Qwen2-0.5B-Instruct
# facebook/nllb-200-distilled-600M
# meta-llama/Llama-3.2-3B-Instruct

python src/finetune.py \
  --model Qwen/Qwen2-1.5B-Instruct \
  --source_language en \
  --target_language de \
  --data_dir data/wmt22 \
  --learn_rate 1e-3 \
  --epochs 1 \
  --batch_size 4 \
  --dtype float16 \
